name: DionTvKentrikisMakedonias (Greece)

on:
  schedule:
    - cron: '0 */3 * * *'
  
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

       
      - name: get config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"
      
      - name: grab twitch stream
        run: |
          pwd
          cd ./core/platforms/
          python3 twitch.py dionthleorash > ../../streams/DionTvKentrikisMakedonias.m3u8
        
      - name: adding everything
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "DionTvKentrikisMakedonias updated (Greece) updated"
          git push
